-- MusicLab Database Schema
-- AJT Semester Project
-- Unit 4 (JDBC/JPA): users, projects, market_tracks, transactions
-- Unit 2 (Java I/O): serialized_data column in projects stores ObjectOutputStream bytes
-- Unit 3 (Networking): transactions table records WebSocket-triggered purchases
-- Run this in Supabase SQL Editor to initialize the database

create table if not exists users (
    id bigint generated by default as identity primary key,
    username varchar(50) not null,
    email varchar(100) not null,
    password_hash varchar(255) not null,
    wallet_balance numeric(12,2) not null default 0.00
);

create table if not exists projects (
    id bigint generated by default as identity primary key,
    project_id varchar(100) not null,
    project_name varchar(150) not null,
    user_id bigint not null,
    serialized_data oid not null,
    created_at timestamp with time zone not null
);

create table if not exists market_tracks (
    id bigint generated by default as identity primary key,
    project_id bigint,
    seller_id bigint not null,
    title varchar(200) not null,
    base_price numeric(10,2) not null,
    listed_at timestamp with time zone not null
);

create table if not exists transactions (
    id bigint generated by default as identity primary key,
    buyer_id bigint not null,
    track_id bigint not null,
    amount_paid numeric(10,2) not null,
    license_type varchar(50) not null,
    transaction_date timestamp with time zone not null
);

create unique index if not exists ux_users_username on users (username);
create unique index if not exists ux_users_email on users (email);
create unique index if not exists ux_projects_project_id on projects (project_id);
create index if not exists ix_projects_user_id on projects (user_id);
create index if not exists ix_market_tracks_seller_id on market_tracks (seller_id);
create index if not exists ix_market_tracks_project_id on market_tracks (project_id);
create index if not exists ix_transactions_buyer_id on transactions (buyer_id);
create index if not exists ix_transactions_track_id on transactions (track_id);

insert into users (username, email, password_hash, wallet_balance)
select 'TestProducer', 'test@musiclab.com', 'hashed_placeholder', 5000.00
where not exists (
    select 1
    from users
    where email = 'test@musiclab.com'
);

insert into market_tracks (project_id, seller_id, title, base_price, listed_at)
select null, u.id, 'Lofi Study Beat', 29.99, now()
from users u
where u.email = 'test@musiclab.com'
  and not exists (
      select 1
      from market_tracks mt
      where mt.seller_id = u.id
        and mt.title = 'Lofi Study Beat'
  );

insert into market_tracks (project_id, seller_id, title, base_price, listed_at)
select null, u.id, 'Cyberpunk Synthwave', 45.50, now()
from users u
where u.email = 'test@musiclab.com'
  and not exists (
      select 1
      from market_tracks mt
      where mt.seller_id = u.id
        and mt.title = 'Cyberpunk Synthwave'
  );

insert into market_tracks (project_id, seller_id, title, base_price, listed_at)
select null, u.id, 'Acoustic Guitar Loop', 15.00, now()
from users u
where u.email = 'test@musiclab.com'
  and not exists (
      select 1
      from market_tracks mt
      where mt.seller_id = u.id
        and mt.title = 'Acoustic Guitar Loop'
  );