-- Core schema migration for MusicLab.
-- This script is idempotent so it can run safely against an already-initialized database.

create table if not exists users (
    id bigint generated by default as identity primary key,
    username varchar(50) not null,
    email varchar(100) not null,
    password_hash varchar(255) not null,
    wallet_balance numeric(12,2) not null
);

create unique index if not exists ux_users_username on users (username);
create unique index if not exists ux_users_email on users (email);

create table if not exists projects (
    id bigint generated by default as identity primary key,
    project_id varchar(100) not null,
    project_name varchar(150) not null,
    user_id bigint not null,
    serialized_data oid not null,
    created_at timestamp with time zone not null
);

create unique index if not exists ux_projects_project_id on projects (project_id);
create index if not exists ix_projects_user_id on projects (user_id);

create table if not exists market_tracks (
    id bigint generated by default as identity primary key,
    project_id bigint,
    seller_id bigint not null,
    title varchar(200) not null,
    base_price numeric(10,2) not null,
    listed_at timestamp with time zone not null
);

create index if not exists ix_market_tracks_seller_id on market_tracks (seller_id);
create index if not exists ix_market_tracks_project_id on market_tracks (project_id);

create table if not exists transactions (
    id bigint generated by default as identity primary key,
    buyer_id bigint not null,
    track_id bigint not null,
    amount_paid numeric(10,2) not null,
    license_type varchar(50) not null,
    transaction_date timestamp with time zone not null
);

create index if not exists ix_transactions_buyer_id on transactions (buyer_id);
create index if not exists ix_transactions_track_id on transactions (track_id);
